// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xlzfvgqfopdlvrolorba.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhsemZ2Z3Fmb3BkbHZyb2xvcmJhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY2OTQ3NDgsImV4cCI6MjA3MjI3MDc0OH0.gCnOE4qaLfzt4B4grx2dM0LGQRwqX--DNRtWKwRwG5g";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});